### ISSUE TITLE
Set min year to 2007 and then update the max year to the current year with javascript

### ISSUE THREAD

**Issue by maxdemaio** [maxdemaio/chess-heat#25]
Specifically this HTML element:

```html
<input class="form-input" id="form-input-year" name="year" type="number" min="2008" max="9999" required />
```

Fix:
https://stackoverflow.com/questions/32378590/set-date-input-fields-max-date-to-today

**Comment by ThienBNguyen** [comment]
Hi maxdemaio, I am interested in the issue. can I try to solve it? thanks

**Comment by ThienBNguyen** [comment]
Hi maxdemaio, I have resolved your issue

**Comment by maxdemaio** [comment]
Hey, @ThienBNguyen! If you'd like to push the commits up to your forked repo and make a PR, go for it! 💪🏻 I'll give it a review and we can merge it in.

**Comment by ThienBNguyen** [comment]
I have created an PR.  it might have indent issue format
