### ISSUE TITLE
Not requesting json

### ISSUE THREAD

**Issue by e6voe9** [maxdemaio/chess-heat#30]
Simply as that. Pgn takes more space than json, there is no need to request whole pgn, when we can request compact json.

**url**: `https://api.chess.com/pub/player/${user}/games/${loopYear}/${loopMonth}/pgn`

**data size with pgn**: ~1578.8kB

![Pasted image 20230504023028](https://user-images.githubusercontent.com/54411613/236086703-106af852-7390-412d-bf4e-d14477ea0491.png)

**url**: `https://api.chess.com/pub/player/${user}/games/${loopYear}/${loopMonth}`

**data size with json**: ~489.3kB

![Pasted image 20230504025757](https://user-images.githubusercontent.com/54411613/236086834-2139c039-e63c-482b-83b5-ec1e148faf22.png)

**~3 times less traffic** and what's more, no more need in RegEx (we all know how slow it is, so potentially faster rendering after receiving data). 
With json we can easily store all data to localStorage and use in future, to optimize more.

**Comment by maxdemaio** [comment]
Nice catch!

I erroneously didn't take the average size in MB of the responses. I'm curious, which user/year did you use?

I only did one sample from GM Hikaru Nakamura 😅:
- `https://api.chess.com/pub/player/hikaru/games/2020/06` (2.5MB)
- `https://api.chess.com/pub/player/hikaru/games/2020/06/pgn` (1.88MB)

I think this would take a good amount of work but I think it'd be well worth it.

**Comment by e6voe9** [comment]
Oh, I see. The point is that json can be well gzipped, and results for whole year for Hikaru are: 
- pgn (11.7MB)
- json (3.5 MB)

![Pasted image 20230504042927](https://user-images.githubusercontent.com/54411613/236098355-ddcd0646-e65f-42d9-80da-9a9ad9969532.png)

![Pasted image 20230504043102](https://user-images.githubusercontent.com/54411613/236098368-08b63f07-a260-449f-b406-4f24b6be35f3.png)

**Comment by e6voe9** [comment]
#34

**Comment by markkhoo** [comment]
Very nice! With the small amount of testing I did I thought pgns were smaller than the json.

**Comment by e6voe9** [comment]
@markkhoo You're not wrong, it's smaller, but slower :)
`/pgn` endpoint meant to be used for downloading pgn files, so there's no compression.
Data from JSON response actually bigger after browser decompression, but traffic data size is 3-4 times smaller.

**Comment by e6voe9** [comment]
I mean, it's just in documentation 

![image](https://user-images.githubusercontent.com/54411613/236274557-edd3357f-15b6-4a10-984b-6a824ed3bb23.png)
