### ISSUE TITLE
Allow all hue values

### ISSUE THREAD

**Issue by maxdemaio** [maxdemaio/chess-heat#37]

**Comment by markkhoo** [comment]
In an attempt to provide the least amount of friction to users who edit the query, we should not give users a way to "break" the query. Any value of hue should be allowed. Useful values should be numbers only and everything else should trigger a default value. Parsed numbers should have a modulus of 360 to fit within the HSL range.

**Comment by maxdemaio** [comment]
Something to also think about: negative values and invalid strings like `?hue=jklsajdflkjklsjnxmnxvlskj` or `?hue=` (empty)

**Comment by markkhoo** [comment]
We could do something like this:

```js
const possible_inputs = [
  '0',
  '-359',
  '360.923',
  '3600000000000000000000000000000000000000000000000000',
  '360blue',
  'blue',
  ''
];

function validateHue(item, default_hue) {
  const num = parseInt(item);
  if (isNaN(num)) {
    return default_hue;
  } else {
    const num_mod = num % 360;
    if (num_mod < 0) {
      return num_mod + 360;
    } else {
      return num_mod
    }
  }
}

possible_inputs.map(str => {
  console.log(validateHue(str, 360))
})
```

Did I miss any other edge cases?
