### ISSUE TITLE
Keyboard accessibility

### ISSUE THREAD

**Issue by e6voe9** [maxdemaio/chess-heat#41]
I would like to be able to cycle through all squares (to see tooltips) using my keyboard pressing `TAB`.

To make any element focusable in html you can add `tabindex="0"` attribute to it.
You can implement it moving mouseover/mouseleave logic from javascript to css. It's possible to make same UX with css `:focus / :hover` effects.

**Reference:** github activity table. Hit `TAB` until you reach first square. Then you can move with arrows.

**Comment by maxdemaio** [comment]
Note: on GitHub, it looks like by default the first square has a tab index of `0`. Then, the rest have a tab index of `-1`. When you select a square, it's tab index is switched to `0` and the previous is switched back to `-1`.
