### ISSUE TITLE
Ability to choose different game classes

### ISSUE THREAD

**Issue by e6voe9** [maxdemaio/chess-heat#45]
Chess has game classes for all time controls.
For example:
180-599 seconds - blitz
600-1800 seconds - rapid
etc.

We can add dropdown which will sort data and show only specific game class chessheat.

In response from `https://api.chess.com/pub/player/{user}/games/{year}/{month}` we are getting `time_class` for every game.

**Comment by maxdemaio** [comment]
Hmmm I'm trying to think of the best way to do this. The best way I can currently think of would be to maintain the gameData in memory even after the `fetchData` function. This way, you can do an O(n) operation on all of the cells to check if we should keep / gray certain squares and update their hues.

**Comment by e6voe9** [comment]
It's not only about updating hues. We should also update values, because 1 player can play for example 1 rapid game and 2 blitz in one day.
I think we should filter gameData and use new array of data to just re-render whole table, because it's too much things to check and update. It doesn't worth to implement reactivity here. It's only 365 squares and ~<10k games per 1 player in a year on average. There are players which has 20k, 30k, but it's not that much for javascript. It still will be fast.

**Comment by e6voe9** [comment]
We should definitely keep last array of data in memory.

**Comment by maxdemaio** [comment]
I think we should keep the original query in memory. For example if you mutate gameData for blitz, you won't have the information on the rapid data anymore if you filter out and replace gameData with that dataset. So long as we keep the original gameData with all of the time control information we should be good 🤔 then we'd just create a mutated copy of the time control data and use that to update the scores/hues.

**Comment by e6voe9** [comment]
Exactly. So for example we have `currentData` as a global variable.
In the render function in order to filter, we don't even have to create a mutated copy, because `.filter()` does it for us. It filters an array and returns new one. It doesn't mutate the original array.

**Comment by e6voe9** [comment]
For example:

```javascript

const filteredData = currentData.filter(game => game.time_class === selectedTimeClass)
renderFunction(filteredData)
```

**Comment by maxdemaio** [comment]
My thought is we could create a second form that will trigger the filtering. We will enable the form (dropdown to filter the games) only once the `fetchData` has completed from submitting the first form. Afterwards, we'll enable the form since the `currentData` has been populated (we'll do a null check too just in case) and then call our render function in the form submit event (when they choose a time control) 🤔
