### ISSUE TITLE
Store last hue value

### ISSUE THREAD

**Issue by e6voe9** [maxdemaio/chess-heat#47]
We don't store user's hue value now. So every time user opens chessheat.com it's 0 by default.
We can store that value in localStorage, to keep last known selected hue.

**Comment by e6voe9** [comment]
What if someone opens the link with hue value passed as a query parameter?
Which one should be higher priority? 
1. parameter
1. stored value

**Comment by maxdemaio** [comment]
I think we'd want the parameter to take priority. This way, when people share links they can have people receive them exactly the way they'd want them to look. So I think if no parameter exists, then we'd default to the stored value. If no stored value exists, then we'd default the hue to 0 as we're doing now 🤔
