### ISSUE TITLE
Submit good user, submit bad user, example hue squares don't change color

### ISSUE THREAD

**Issue by maxdemaio** [maxdemaio/chess-heat#60]
STR:
- Submit good user `max_mayo`
- Submit bad user `max_mayo02340`
- Attempt to slide hue range

Expected: hues on the example squares update
Actual: hues on example squares stay what they were from the successful user

<img width="1031" alt="image" src="https://github.com/maxdemaio/chess-heat/assets/44373521/5d33f471-8051-4ec3-8e72-569182512f05">

**Comment by e6voe9** [comment]
I think you can just remove this code and make this 4 cells use color from vars in css. Two of that vars already are in css file: `--color-alpha`, `--color-alpha-dark`.

```javascript

// Update example cells
  exampleCells.forEach((ex) => {
    const hslValues = ex.dataset.hsl.split(',');
    const saturation = hslValues[1];
    const lightness = hslValues[2];
    ex.style.color = `hsl(${hue}, ${saturation}%, ${lightness}%)`;
  });
```


In css add this vars and use them
```css

--color-0: hsl(var(--hue), 79%, 66%);
--color-4: hsl(var(--hue), 51%, 11%);
```
